In [3]:
import numpy as np
a = np.zeros((1,10))
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

a = np.zeros((1,10))
nx,ny = a.shape
print('nx =', nx)

a = np.zeros(8) + 16
b = np.ones(8) * 16
c = np.full((2,8), 16)
print(a, '\n')
print(b, '\n')
print(c, '\n')

a = np.eye(5)
print(a, '\n')

a = np.array([[2,3,4,5,6,7,8], [20,30,40,50,60,70,80], [200,300,400,500,600,700,800]])
print(a, '\n')

b = a[0, :]
print(b, '\n')
b = a[1, :]
print(b, '\n')
b = a[2, :]
print(b, '\n')

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

len = 1
shape = (1, 10)
nx = 1
[16. 16. 16. 16. 16. 16. 16. 16.] 

[16. 16. 16. 16. 16. 16. 16. 16.] 

[[16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[  2   3   4   5   6   7   8]
 [ 20  30  40  50  60  70  80]
 [200 300 400 500 600 700 800]] 

[2 3 4 5 6 7 8] 

[20 30 40 50 60 70 80] 

[200 300 400 500 600 700 800] 

