In [1]:
import numpy as np
a = np.arange(21)
print(a)

# use random numbers to populate an array
ranNum = np.random.rand(8)
print(ranNum)

LING = np.zeros(16)
YI = np.ones(24)
ER = np.ones(24)*3
print(LING)
print(YI)
print(ER)

a = np.arange(24)+1
print(a)
print(a[0])
print(a[1:4])
print(a[2:6])
print(a[3:8])
print(a[4:10])
print(a[5:12])
print(a[6:14])
print(a[7:16])
print(a[8:18])
print(a[9:20])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0.78073787 0.32122678 0.59171348 0.79843057 0.7923627  0.72584228
 0.37754005 0.77991045]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
1
[2 3 4]
[3 4 5 6]
[4 5 6 7 8]
[ 5  6  7  8  9 10]
[ 6  7  8  9 10 11 12]
[ 7  8  9 10 11 12 13 14]
[ 8  9 10 11 12 13 14 15 16]
[ 9 10 11 12 13 14 15 16 17 18]
[10 11 12 13 14 15 16 17 18 19 20]
